services:
  medsmart-db-dev:
    container_name: medsmart-db-dev
    image: postgres:latest
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - medsmart-dev
volumes:
  postgres_data:
networks:
  medsmart-dev:
